#
# Copyright (C) 2013 Sam Kottler <shk@linux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
---
- name: Setup the requirements and the instance
  hosts: all
  tags:
    - setup

  vars_files:
    - variables.yml

  tasks:
  - name: install requirements
    action: yum pkg=$item state=installed
    with_items:
    - httpd
    - php
    - php-mysql
    - php-mbstring
    - php-xml
    - mysql-server
    - MySQL-python
    - git
    - system-config-firewall-base

  - name: ensure httpd is running
    action: service name=httpd state=started enabled=true

  - name: allow our ports
    action: command /usr/sbin/lokkit $item
    with_items:
    - --service=ssh
    - --service=https
    - --service=http
    
  - name: bring up mysql
    action: service name=mysqld state=started enabled=true

- name: Configuration ttrss
  hosts: all
  tags: 
    - config

  vars_files:
    - variables.yml

  tasks:
  - name: ttrss user in mysql
    action: mysql_user user=$db_user password=$db_password priv=*.*:ALL state=present

  - name: create ttrss db
    action: mysql_db db=ttrss state=present

  - name: ensure the ttrss docroot exists and is the right context
    action: file dest=$docroot mode=0755 state=directory context=public_content_rw_t

  - name: checkout the ttrss source code from git
    action: git repo=https://github.com/gothfox/Tiny-Tiny-RSS.git dest=$docroot 

  - name: import the db schema
    action: shell creates=/etc/ttrss-db-imported mysql -u root ttrss < $docroot/schema/ttrss_schema_mysql.sql

  - name : create the cache dirs
    action: file dest=${docroot}/${item}  mode=777 state=directory context=public_content_rw_t
    with_items:
    - cache/images
    - cache/export
    - feed-icons
    - lock
  - name: make SURE the context is correct
    action: command chcon -t public_content_rw_t $item
    with_items:
    - $docroot/cache/images
    - $docroot/cache/export
    - $docroot/feed-icons
    - $docroot/lock
    - $docroot

  - name: set the selinux bool for apache anon writes
    action: seboolean name=httpd_anon_write state=true persistent=yes

  - name: create the tt-rss configuration file
    action: template src=config.j2 dest=$docroot/config.php
    notify:
    - restart httpd

  handlers:
    - include: handlers.yml
